name: waktusolatmalaysia
description: App waktu solat seluruh Malaysia

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.12.82-beta+38

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^0.1.3
  http: ^0.12.2
  intl: ^0.16.1
  google_fonts: ^1.1.0
  fluttertoast: ^7.0.2
  hijri: ^2.0.3
  package_info: ^0.4.3
  get_storage: ^1.3.0
  cached_network_image: ^2.3.1
  url_launcher: ^5.5.1
  device_info: ^1.0.0
  share: ^0.6.5
  geolocator: ^6.0.0+4
  flutter_spinkit: ^4.1.2+1
  get: ^3.12.1
  flutter_svg: ^0.19.0
  auto_size_text: ^2.1.0
  provider: ^4.3.2+2
  flutter_local_notifications: ^3.0.1+5
  rxdart: ^0.24.1
  app_settings: ^4.0.4
  isolate_handler: ^0.3.1
  flutter_web_browser: ^0.13.0
  geocoding: ^1.0.5
  font_awesome_flutter: ^8.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/svgIcons/
  #   - assets/grouped.json

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
