name: waktusolatmalaysia
description: App waktu solat seluruh Malaysia

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.26.138-pre.6+65

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^0.1.3
  http: ^0.13.1
  intl: ^0.17.0
  google_fonts: ^2.0.0
  fluttertoast: ^8.0.3
  hijri:
    git: https://github.com/iqfareez/hijri_date.git
  package_info: ^2.0.0
  get_storage: ^2.0.1
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.3
  device_info: ^2.0.0
  share: ^2.0.1
  geolocator: ^7.0.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  auto_size_text: ^3.0.0-nullsafety.0
  provider: ^5.0.0
  flutter_local_notifications: ^6.0.0
  app_settings: ^4.1.0
  isolate_handler: ^1.0.0
  flutter_web_browser: ^0.15.0
  geocoding: ^2.0.0
  font_awesome_flutter: ^9.0.0
  flutter_qiblah: ^2.0.1
  cloud_firestore: ^2.1.0
  firebase_core: ^1.0.2
  email_validator: ^2.0.1
  introduction_screen: ^2.1.0
  firebase_remote_config: ^0.10.0+3
  in_app_review: ^2.0.2
  google_mobile_ads: ^0.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/qibla/
    - assets/bam/
  #   - assets/grouped.json

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
