name: waktusolatmalaysia
description: App waktu solat seluruh Malaysia

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.8.1+128

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.1
  intl: ^0.18.0
  google_fonts: ^4.0.1
  fluttertoast: ^8.0.3
  package_info_plus: ^4.0.0
  get_storage: ^2.0.1
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.3
  device_info_plus: ^9.0.0
  share_plus: ^7.0.0
  geolocator: ^9.0.2
  flutter_spinkit: ^5.0.0
  flutter_svg: ^2.0.0
  provider: ^6.0.0
  flutter_local_notifications: ^14.0.0+1
  app_settings: ^4.1.0
  flutter_web_browser: ^0.17.0
  geocoding: ^2.0.0
  font_awesome_flutter: ^10.1.0
  flutter_qiblah: ^2.0.1
  firebase_core: ^2.2.0
  email_validator: ^2.0.1
  introduction_screen: ^3.0.0
  in_app_review: ^2.0.2
  google_mobile_ads: ^3.0.0
  restart_app: ^1.0.3
  flutter_markdown: ^0.6.9
  firebase_analytics: ^10.0.5
  auto_start_flutter:
    # Issue https://github.com/seena98/auto_start_flutter/issues/6
    git: https://github.com/iqfareez/auto_start_flutter.git
  timezone: ^0.9.0
  quick_actions: ^1.0.0
  firebase_crashlytics: ^3.0.5
  dynamic_color: ^1.6.2

dependency_overrides:
  # flutter compass in pub.dev is not updated
  flutter_compass:
    git: https://github.com/hemanthrajv/flutter_compass.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/qibla/
    - assets/3d/
    - assets/OFL.txt
    - assets/json/
  #   - assets/grouped.json
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyMptIcons
      fonts:
        - asset: assets/fonts/MyMptIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
