name: waktusolatmalaysia
description: App waktu solat seluruh Malaysia

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# After update this value, check the flutter version in the [environment.flutter]
version: 2.12.4+149

environment:
  sdk: ">=3.0.0 <4.0.0"
  # Purely used in CI workflow that have [flutter-version-file] specified
  # Put this version same as the version used in development environment to have predictable output
  flutter: 3.22.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: 0.19.0
  google_fonts: ^6.1.0
  fluttertoast: ^8.0.3
  package_info_plus: ^8.0.0
  get_storage: ^2.0.1
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.3
  device_info_plus: ^10.1.0
  share_plus: ^10.0.0
  geolocator: ^11.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^2.0.0
  provider: ^6.0.0
  flutter_local_notifications: ^17.1.0
  app_settings: ^5.0.0
  flutter_web_browser: ^0.17.0
  geocoding: ^3.0.0
  font_awesome_flutter: ^10.1.0
  flutter_qiblah: ^3.0.3
  firebase_core: ^3.2.0
  email_validator: ^3.0.0
  introduction_screen: ^3.0.0
  in_app_review: ^2.0.2
  google_mobile_ads: ^5.0.0
  restart_app: ^1.0.3
  flutter_markdown: ^0.7.1
  firebase_analytics: ^11.2.0
  auto_start_flutter:
    # Issue https://github.com/seena98/auto_start_flutter/issues/6
    git: https://github.com/iqfareez/auto_start_flutter.git
  timezone: ^0.9.0
  quick_actions: ^1.0.0
  firebase_crashlytics: ^4.0.3
  dynamic_color: ^1.6.2
  flutter_staggered_animations: ^1.1.1
  path_provider: ^2.1.1
  open_file: ^3.3.2
  home_widget: ^0.6.0
  permission_handler: ^11.3.1
  hotspot: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/qibla/
    - assets/3d/
    - assets/OFL.txt
    - assets/json/
  #   - assets/grouped.json
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # Adding custom icon guide: https://github.com/mptwaktusolat/app_waktu_solat_malaysia/wiki/Custom-Icons
    - family: MyMptIcons
      fonts:
        - asset: assets/fonts/MyMptIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
